# Generated by Django 4.1.7 on 2023-04-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_bookingdate_booking_bookingdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingDate',
            new_name='BookingDate',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_guests',
            new_name='No_of_guests',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='inventory',
            new_name='Inventory',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menuID',
            new_name='MenuID',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='Title',
        ),
    ]
